required = ["github.com/golang/protobuf/protoc-gen-go"]
[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.12.0"
#
#[[constraint]]
#  name = "github.com/golang/protobuf"
#  revision = "v1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "7b2c5ac9fc04fc5efafb60700713d4fa609b777b" # cobra has no release tags at time of writing

#[[constraint]]
#  name = "github.com/google/gopacket"
#  revision = "v1.1.14"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "v2.2.1"
